// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdoheyTRand-pYn_IZ6a0t9-z1BnkTeVE',
    appId: '1:632670708082:web:1492a242bf589054b87deb',
    messagingSenderId: '632670708082',
    projectId: 'official-twitter-clone-2026',
    authDomain: 'official-twitter-clone-2026.firebaseapp.com',
    storageBucket: 'official-twitter-clone-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFQSyXv2axH_iyN3c96qfk0L0v9i6Xtc',
    appId: '1:632670708082:android:8f699f4ce20099f6b87deb',
    messagingSenderId: '632670708082',
    projectId: 'official-twitter-clone-2026',
    storageBucket: 'official-twitter-clone-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAC4WwDN9SM4v5daOAH_APWkzFGcFDcs',
    appId: '1:632670708082:ios:dea1d50259999620b87deb',
    messagingSenderId: '632670708082',
    projectId: 'official-twitter-clone-2026',
    storageBucket: 'official-twitter-clone-2026.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAC4WwDN9SM4v5daOAH_APWkzFGcFDcs',
    appId: '1:632670708082:ios:dea1d50259999620b87deb',
    messagingSenderId: '632670708082',
    projectId: 'official-twitter-clone-2026',
    storageBucket: 'official-twitter-clone-2026.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdoheyTRand-pYn_IZ6a0t9-z1BnkTeVE',
    appId: '1:632670708082:web:a1fd7666e1903bcfb87deb',
    messagingSenderId: '632670708082',
    projectId: 'official-twitter-clone-2026',
    authDomain: 'official-twitter-clone-2026.firebaseapp.com',
    storageBucket: 'official-twitter-clone-2026.firebasestorage.app',
  );
}
